export const rows = [
  {
    id: 1,
    avatar: '8.png',
    full_name: 'Anivasi',
    post: 'Nuclear Power Engineer',
    email: 'Anivasi',
    city: 'Bigar Nivasi',
    start_date: '09/23/2016',
    salary: 23896.35,
    age: '61',
    experience: '1 Year',
    status: 2
  },
  {
    id: 1,
    avatar: '8.png',
    full_name: 'Nivasi',
    post: 'Nuclear Power Engineer',
    email: 'Nivasi',
    city: 'Nivasi',
    start_date: '09/23/2016',
    salary: 23896.35,
    age: '61',
    experience: '1 Year',
    status: 2
  },
  {
    id: 1,
    avatar: '8.png',
    full_name: 'Anivasi',
    post: 'Nuclear Power Engineer',
    email: 'Anivasi',
    city: 'Bigar Nivasi',
    start_date: '09/23/2016',
    salary: 23896.35,
    age: '61',
    experience: '1 Year',
    status: 2
  },
  {
    id: 1,
    avatar: '8.png',
    full_name: 'Anivasi',
    post: 'Nuclear Power Engineer',
    email: 'Anivasi',
    city: 'Bigar Nivasi',
    start_date: '09/23/2016',
    salary: 23896.35,
    age: '61',
    experience: '1 Year',
    status: 2
  },
  {
    id: 1,
    avatar: '8.png',
    full_name: 'Anivasi',
    post: 'Nuclear Power Engineer',
    email: 'Anivasi',
    city: 'Bigar Nivasi',
    start_date: '09/23/2016',
    salary: 23896.35,
    age: '61',
    experience: '1 Year',
    status: 2
  },
  {
    id: 1,
    avatar: '8.png',
    full_name: 'Anivasi',
    post: 'Nuclear Power Engineer',
    email: 'Anivasi',
    city: 'Bigar Nivasi',
    start_date: '09/23/2016',
    salary: 23896.35,
    age: '61',
    experience: '1 Year',
    status: 2
  },
  {
    id: 1,
    avatar: '8.png',
    full_name: 'Anivasi',
    post: 'Nuclear Power Engineer',
    email: 'Anivasi',
    city: 'Bigar Nivasi',
    start_date: '09/23/2016',
    salary: 23896.35,
    age: '61',
    experience: '1 Year',
    status: 2
  },
  {
    id: 1,
    avatar: '8.png',
    full_name: 'Anivasi',
    post: 'Nuclear Power Engineer',
    email: 'Anivasi',
    city: 'Bigar Nivasi',
    start_date: '09/23/2016',
    salary: 23896.35,
    age: '61',
    experience: '1 Year',
    status: 2
  },
  {
    id: 1,
    avatar: '8.png',
    full_name: 'Anivasi',
    post: 'Nuclear Power Engineer',
    email: 'Anivasi',
    city: 'Bigar Nivasi',
    start_date: '09/23/2016',
    salary: 23896.35,
    age: '61',
    experience: '1 Year',
    status: 2
  },
  {
    id: 1,
    avatar: '8.png',
    full_name: 'Anivasi',
    post: 'Nuclear Power Engineer',
    email: 'Anivasi',
    city: 'Bigar Nivasi',
    start_date: '09/23/2016',
    salary: 23896.35,
    age: '61',
    experience: '1 Year',
    status: 2
  }
]
